import type { Metadata } from "next";
import Link from "next/link";
import {
  ArrowRight, CheckCircle2, Eye, TrendingUp, Bell, Mail, BarChart2,
  Search, Globe, Star, MessageSquare, Smartphone, Calendar, Zap, Lock
} from "lucide-react";
import SectionWrapper from "@/components/SectionWrapper";
import CTABanner from "@/components/CTABanner";
import { breadcrumbSchema, serviceSchema } from "@/lib/schema";

const PAGE_URL = "https://datalatte.pro/services/competitor-analysis";

export const metadata: Metadata = {
  title: "AI Competitor Analysis for Local Businesses | DataLatte",
  description:
    "Track your local competitors automatically — their Google rankings, reviews, social content, ads, and pricing — and receive weekly AI-powered reports straight to your inbox or WhatsApp.",
  alternates: {
    canonical: PAGE_URL,
    languages: {
      "en-US": PAGE_URL,
      "en-GB": PAGE_URL,
      "en-AU": PAGE_URL,
      "en-CA": PAGE_URL,
      "x-default": PAGE_URL,
    },
  },
  openGraph: {
    title: "AI Competitor Analysis for Local Businesses | DataLatte",
    description:
      "Track your local competitors automatically — their Google rankings, reviews, social content, ads, and pricing — and receive weekly AI-powered reports straight to your inbox or WhatsApp.",
    url: PAGE_URL,
    siteName: "DataLatte",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Competitor Analysis for Local Businesses | DataLatte",
    description: "Track your local competitors automatically — weekly AI reports to inbox or WhatsApp.",
  },
};

const TRACKED = [
  {
    icon: Search,
    label: "Google Rankings",
    detail: "Track their position for your shared keywords — see when they rise or drop",
  },
  {
    icon: Star,
    label: "Reviews & Ratings",
    detail: "Every new Google review they receive, with sentiment analysis",
  },
  {
    icon: Globe,
    label: "Website Changes",
    detail: "Pricing updates, new offers, homepage changes — caught within 24h",
  },
  {
    icon: Smartphone,
    label: "Social Media Content",
    detail: "Instagram, Facebook, TikTok — what they post, what performs best",
  },
  {
    icon: BarChart2,
    label: "Ad Activity",
    detail: "When competitors start or stop running Google and Meta ads",
  },
  {
    icon: MessageSquare,
    label: "GBP Activity",
    detail: "New Google Business Profile posts, Q&A, and service updates",
  },
];

const REPORTS = [
  {
    frequency: "Daily",
    icon: Bell,
    color: "text-red-500",
    bg: "bg-red-50 border-red-100",
    desc: "Instant alert when a competitor launches a new ad, drops prices, or gets a 1-star review. Act before they gain the advantage.",
    delivery: "WhatsApp or SMS",
    available: "Add-on",
  },
  {
    frequency: "Weekly",
    icon: TrendingUp,
    color: "text-coffee-600",
    bg: "bg-coffee-50 border-coffee-100",
    desc: "7-day summary of competitor activity — top posts, ranking changes, review trends, and a 3-bullet action plan generated by AI.",
    delivery: "Email or WhatsApp",
    available: "Americano & above",
  },
  {
    frequency: "Monthly",
    icon: BarChart2,
    color: "text-gray-600",
    bg: "bg-gray-50 border-gray-100",
    desc: "Full competitive landscape report with share-of-voice, review gap analysis, keyword comparison, and strategic recommendations.",
    delivery: "Email PDF",
    available: "All packages",
  },
];

const HOW_IT_WORKS = [
  {
    step: "01",
    title: "We identify your competitors",
    desc: "You provide a list of 3–5 local competitors, or we research the market and find the businesses actually competing for your customers.",
  },
  {
    step: "02",
    title: "AI agent starts monitoring",
    desc: "Our agent — powered by the latest Claude model — scrapes their Google profiles, social media, website, ads library, and review platforms on a daily schedule.",
  },
  {
    step: "03",
    title: "Data is analysed and summarised",
    desc: "Raw data is fed into a structured analysis pipeline. The AI identifies patterns, spots opportunities, and flags threats — no spreadsheets for you.",
  },
  {
    step: "04",
    title: "Report lands in your inbox",
    desc: "Clean, readable reports arrive weekly (and monthly) in your email or WhatsApp. Daily alerts fire instantly for high-priority events.",
  },
];

const FAQS = [
  {
    q: "How many competitors can you track?",
    a: "The standard setup covers 3–5 local competitors. If you want to monitor more — for example, if you operate in multiple locations — we can expand the scope as part of the Pumpkin Spice Latte package.",
  },
  {
    q: "Is this available as a standalone service?",
    a: "Competitor monitoring is included in the Americano and Pumpkin Spice Latte packages. For the Espresso package, it's available as an add-on ($150/month). We don't currently offer it as a completely standalone service without an existing package.",
  },
  {
    q: "Which social platforms do you monitor?",
    a: "Instagram, Facebook, TikTok, and Google Business Profile by default. LinkedIn monitoring is available for B2B-adjacent businesses on request.",
  },
  {
    q: "How quickly are alerts sent?",
    a: "The monitoring agent runs checks every 4–6 hours. Most alerts are delivered within a few hours of the event. Website changes are checked daily.",
  },
  {
    q: "Can I get reports on WhatsApp?",
    a: "Yes — WhatsApp delivery is available for weekly summaries and instant alerts. We set up a dedicated WhatsApp connection as part of onboarding.",
  },
  {
    q: "Is competitor data collection legal?",
    a: "Yes. We only monitor publicly available information — Google search results, public social media profiles, publicly visible websites, and the Google Ads Transparency Center. We don't access any private or restricted data.",
  },
];

export default function CompetitorAnalysisPage() {
  const breadcrumb = breadcrumbSchema([
    { name: "Home", url: "https://datalatte.pro" },
    { name: "Services", url: "https://datalatte.pro/services" },
    { name: "AI Competitor Analysis", url: PAGE_URL },
  ]);
  const service = serviceSchema({
    name: "AI Competitor Analysis for Local Businesses",
    description: "Automated competitor tracking powered by AI — covering Google rankings, reviews, social media, ads, and website changes. Weekly and monthly reports delivered to email or WhatsApp.",
    url: PAGE_URL,
  });

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(service) }} />

      {/* ── Hero ── */}
      <section className="relative bg-gray-900 overflow-hidden py-24 px-4 sm:px-6 lg:px-8">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-coffee-800/30 via-transparent to-transparent pointer-events-none" />
        <div className="relative max-w-4xl mx-auto text-center">
          <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-coffee-700/20 border border-coffee-700/30 text-coffee-300 text-xs font-semibold uppercase tracking-wider mb-6">
            <Zap size={11} /> Powered by AI · Included in Americano
          </span>
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-white mb-6 leading-tight">
            Know exactly what your{" "}
            <span className="text-coffee-400">competitors are doing</span>
            {" "}— before your customers do
          </h1>
          <p className="text-xl text-gray-300 mb-10 max-w-2xl mx-auto">
            An AI agent monitors your local competitors 24/7 across Google, social media, their website, and ad platforms — then sends you a clear, actionable report every week.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/free-audit" className="btn-primary">
              Get competitor analysis <ArrowRight size={16} />
            </Link>
            <Link href="/pricing" className="inline-flex items-center gap-2 px-6 py-3 border border-gray-600 text-gray-300 rounded-xl hover:border-gray-400 hover:text-white transition-colors font-medium">
              See pricing
            </Link>
          </div>
        </div>
      </section>

      {/* ── What we track ── */}
      <SectionWrapper>
        <div className="text-center mb-12">
          <span className="section-label">What we monitor</span>
          <h2 className="section-title">Every move your competitors make</h2>
          <p className="section-subtitle">
            Six data sources. One clean report. Delivered to your inbox every week.
          </p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {TRACKED.map((item) => (
            <div key={item.label} className="bg-white rounded-2xl border border-gray-100 p-6 shadow-sm hover:shadow-md transition-shadow">
              <div className="w-10 h-10 rounded-xl bg-coffee-50 border border-coffee-100 flex items-center justify-center mb-4">
                <item.icon size={20} className="text-coffee-700" />
              </div>
              <h3 className="font-semibold text-gray-900 mb-2">{item.label}</h3>
              <p className="text-sm text-gray-500">{item.detail}</p>
            </div>
          ))}
        </div>
      </SectionWrapper>

      {/* ── Sample report preview ── */}
      <section className="bg-gray-50 py-20 px-4 sm:px-6 lg:px-8 border-y border-gray-100">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <span className="section-label">Report preview</span>
            <h2 className="section-title">What your weekly report looks like</h2>
          </div>

          {/* Mock report card */}
          <div className="bg-white rounded-3xl border border-gray-200 shadow-xl overflow-hidden">
            {/* Report header */}
            <div className="bg-gray-900 px-8 py-5 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-coffee-700 flex items-center justify-center text-white text-sm font-bold">D</div>
                <div>
                  <p className="text-white text-sm font-semibold">Weekly Competitor Report</p>
                  <p className="text-gray-400 text-xs">Sunrise Coffee Co. · May 19–26, 2026</p>
                </div>
              </div>
              <span className="text-xs text-gray-500 bg-gray-800 px-3 py-1 rounded-full">3 competitors tracked</span>
            </div>

            <div className="p-8 space-y-8">
              {/* Summary row */}
              <div className="grid grid-cols-3 gap-4">
                {[
                  { label: "New competitor reviews", value: "14", delta: "+3 vs last week", up: false },
                  { label: "Competitor ad activity", value: "2 active", delta: "Bean & Grind started ads", up: false },
                  { label: "Keyword ranking shifts", value: "5 changes", delta: "You gained on 3 terms", up: true },
                ].map((s) => (
                  <div key={s.label} className="bg-gray-50 rounded-2xl p-4 text-center">
                    <p className="text-2xl font-bold text-gray-900">{s.value}</p>
                    <p className="text-xs text-gray-500 mt-1">{s.label}</p>
                    <p className={`text-xs font-medium mt-2 ${s.up ? "text-green-600" : "text-amber-600"}`}>{s.delta}</p>
                  </div>
                ))}
              </div>

              {/* AI insight */}
              <div className="bg-coffee-50 border border-coffee-100 rounded-2xl p-6">
                <div className="flex items-start gap-3">
                  <div className="w-7 h-7 rounded-lg bg-coffee-700 flex items-center justify-center flex-shrink-0 mt-0.5">
                    <Zap size={13} className="text-white" />
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-coffee-900 mb-2">AI Analysis — This Week&apos;s Key Insight</p>
                    <p className="text-sm text-coffee-800 leading-relaxed">
                      <strong>Bean &amp; Grind</strong> launched Google Ads on Monday targeting &quot;coffee shop downtown [city]&quot; — a term where you currently rank #4 organically. Their ad is running a &quot;Free pastry with first order&quot; promotion. <strong>Recommended action:</strong> Activate your dormant Google Ads campaign this week targeting the same keywords. Their offer is time-limited; yours doesn&apos;t need to be.
                    </p>
                  </div>
                </div>
              </div>

              {/* Competitor cards */}
              <div>
                <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-4">Competitor Activity</p>
                <div className="space-y-3">
                  {[
                    { name: "Bean & Grind", change: "Started Google Ads · 3 new 5★ reviews · Posted 4x on Instagram", alert: true },
                    { name: "The Daily Grind", change: "Updated menu prices · 1 new review (3★) · No social activity", alert: false },
                    { name: "Café Moreno", change: "Running Meta retargeting ads · Published a new blog post", alert: false },
                  ].map((c) => (
                    <div key={c.name} className={`flex items-start gap-3 rounded-xl p-4 border ${c.alert ? "bg-amber-50 border-amber-100" : "bg-gray-50 border-gray-100"}`}>
                      <div className={`w-2 h-2 rounded-full mt-2 flex-shrink-0 ${c.alert ? "bg-amber-400" : "bg-gray-300"}`} />
                      <div>
                        <p className="text-sm font-semibold text-gray-900">{c.name}</p>
                        <p className="text-sm text-gray-600">{c.change}</p>
                      </div>
                      {c.alert && <span className="ml-auto text-xs font-semibold text-amber-700 bg-amber-100 px-2 py-0.5 rounded-full whitespace-nowrap">Action needed</span>}
                    </div>
                  ))}
                </div>
              </div>

              {/* Blur overlay for bottom */}
              <div className="relative">
                <div className="opacity-30 blur-sm pointer-events-none select-none space-y-3">
                  <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider">Keyword Rankings · Social Performance · Review Gap Analysis</p>
                  <div className="h-4 bg-gray-100 rounded w-3/4" />
                  <div className="h-4 bg-gray-100 rounded w-1/2" />
                  <div className="h-4 bg-gray-100 rounded w-2/3" />
                </div>
                <div className="absolute inset-0 flex items-center justify-center">
                  <Link href="/pricing" className="flex items-center gap-2 bg-gray-900 text-white px-5 py-2.5 rounded-xl text-sm font-semibold hover:bg-gray-700 transition-colors shadow-lg">
                    <Lock size={13} /> Unlock full report — see pricing
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Report types ── */}
      <SectionWrapper>
        <div className="text-center mb-12">
          <span className="section-label">Report cadence</span>
          <h2 className="section-title">Daily, weekly, or monthly — your choice</h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {REPORTS.map((r) => (
            <div key={r.frequency} className={`rounded-2xl border p-6 ${r.bg}`}>
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2">
                  <r.icon size={18} className={r.color} />
                  <span className="font-bold text-gray-900">{r.frequency}</span>
                </div>
                <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${r.available === "Add-on" ? "bg-gray-100 text-gray-600" : "bg-coffee-100 text-coffee-700"}`}>
                  {r.available}
                </span>
              </div>
              <p className="text-sm text-gray-600 mb-4">{r.desc}</p>
              <div className="flex items-center gap-2 text-xs text-gray-500">
                <Mail size={12} />
                <span>{r.delivery}</span>
              </div>
            </div>
          ))}
        </div>
      </SectionWrapper>

      {/* ── How it works ── */}
      <section className="bg-gray-50 py-20 px-4 sm:px-6 lg:px-8 border-y border-gray-100">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <span className="section-label">How it works</span>
            <h2 className="section-title">Set up once. Runs forever.</h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {HOW_IT_WORKS.map((step) => (
              <div key={step.step} className="bg-white rounded-2xl border border-gray-100 p-6 shadow-sm">
                <span className="text-4xl font-black text-coffee-100 leading-none">{step.step}</span>
                <h3 className="font-semibold text-gray-900 mt-2 mb-2">{step.title}</h3>
                <p className="text-sm text-gray-500">{step.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Pricing inclusion ── */}
      <SectionWrapper>
        <div className="text-center mb-12">
          <span className="section-label">Included in</span>
          <h2 className="section-title">Available across all packages</h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-4xl mx-auto">
          {[
            {
              name: "Espresso",
              price: "From $500/mo",
              highlight: false,
              includes: "Monthly competitor report",
              addon: "Daily alerts & weekly reports: +$150/mo",
            },
            {
              name: "Americano",
              price: "From $1,200/mo",
              highlight: true,
              includes: "Weekly + monthly reports included",
              addon: "Daily alerts: +$100/mo",
            },
            {
              name: "Pumpkin Spice Latte",
              price: "From $2,500/mo",
              highlight: false,
              includes: "Daily alerts + weekly + monthly reports",
              addon: "All included — nothing extra",
            },
          ].map((tier) => (
            <div key={tier.name} className={`rounded-2xl border p-6 ${tier.highlight ? "border-coffee-700 ring-2 ring-coffee-700 bg-coffee-50" : "border-gray-200 bg-white"}`}>
              <p className={`text-sm font-bold mb-1 ${tier.highlight ? "text-coffee-700" : "text-gray-900"}`}>{tier.name}</p>
              <p className="text-xs text-gray-500 mb-4">{tier.price}</p>
              <div className="flex items-start gap-2 mb-3">
                <CheckCircle2 size={15} className="text-green-500 flex-shrink-0 mt-0.5" />
                <p className="text-sm text-gray-700">{tier.includes}</p>
              </div>
              <p className="text-xs text-gray-400 border-t border-gray-100 pt-3 mt-3">{tier.addon}</p>
            </div>
          ))}
        </div>
        <div className="text-center mt-8">
          <Link href="/pricing" className="btn-primary">
            View full pricing <ArrowRight size={16} />
          </Link>
        </div>
      </SectionWrapper>

      {/* ── FAQ ── */}
      <section className="bg-gray-50 py-20 px-4 sm:px-6 lg:px-8 border-t border-gray-100">
        <div className="max-w-2xl mx-auto">
          <div className="text-center mb-12">
            <span className="section-label">FAQ</span>
            <h2 className="section-title">Common questions</h2>
          </div>
          <div className="space-y-4">
            {FAQS.map((faq) => (
              <div key={faq.q} className="bg-white rounded-2xl border border-gray-100 p-6">
                <h3 className="font-semibold text-gray-900 mb-2">{faq.q}</h3>
                <p className="text-sm text-gray-600 leading-relaxed">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <CTABanner
        headline="Ready to know what your competitors are doing?"
        sub="We'll set up your competitor monitoring as part of onboarding — no extra effort required from you."
        ctaLabel="Get started today"
        ctaHref="/contact"
      />
    </>
  );
}
